name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'
  workflow_dispatch:
  push:
    paths:
      - '**/Day_*.php'
jobs:
  update:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'TheSylwio')
    steps:
      - uses: actions/checkout@v2
      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: 📤 Push
        with:
          commit_message: Update badges
          file_pattern: README.md
